ucsb-cs156-f24/team02-f24-05

- src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
- src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
- src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
- src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItem.json
- src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
Closes #8 
Copied backend files into the new repo to get ready for the rest of team02
> added DCMI backend files from team-01

- src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestController.java
- src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
- src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
- src/main/resources/db/migration/changes/HelpRequest.json
- src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestControllerTests.java
Closes #44 
- Copied over all necessary files for backend operations
- Working successfully on localhost and personal dokku deployment
> Copy Files for Backend CRUD API HelpRequest

- frontend/src/fixtures/ucsbDiningCommonsMenuItemFixtures.js
Closes #9 
- Created ucsbDiningCommonsMenuItemFixtures.js
- Changed format to have correct json for DCMI data
> added fixtures file for DCMI

- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/docs-index/_config.yml
- frontend/docs-index/_layouts/default.html
- frontend/docs-index/index.md
- frontend/jsconfig.json
- frontend/public/index.html
- frontend/public/mockServiceWorker.js
- frontend/src/fixtures/menuItemReviewFixtures.js
- frontend/src/fixtures/temp.json
- frontend/src/index.css
- frontend/stryker.config.json
Close #36 
created fixtures file
> created fixtures

- frontend/public/mockServiceWorker.js
- frontend/src/fixtures/articlesFixtures.js
- src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
- src/main/java/edu/ucsb/cs156/example/entities/Article.java
- src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java
- src/main/resources/db/migration/changes/Articles.json
- src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java
Closes #54 
Added articles file that represents the JSON object returned from the GET endpoint of the articles table
> Add Articles Fixtures

- frontend/public/mockServiceWorker.js
- src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
- src/main/java/edu/ucsb/cs156/example/entities/Article.java
- src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java
- src/main/resources/db/migration/changes/Articles.json
- src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java
Closes #53 
Added the following 5 files which create the articles database table and add endpoints to interact with it: 
- Articles.java
- ArticlesRepository.java
- ArticlesController.java
- ArticlesControllerTests.java
- Articles.json
> Add articles table

- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/docs-index/_config.yml
- frontend/docs-index/_layouts/default.html
- frontend/docs-index/index.md
- frontend/jsconfig.json
- frontend/public/index.html
- frontend/public/mockServiceWorker.js
- frontend/src/fixtures/recommendationRequestFixtures.js
- frontend/src/fixtures/temp.json
- frontend/src/index.css
- frontend/stryker.config.json
> Added fixtures for RecommendationRequest

- frontend/src/main/components/Articles/ArticlesForm.js
- frontend/src/stories/components/Articles/ArticlesForm.stories.js
- frontend/src/tests/components/Articles/ArticlesForm.test.js
Closes #55 
- Added ArticlesForm.test.js
- Added ArticlesForm.js
- Added ArticlesForm.stories.js
Code passes all mutation tests
> Form component for articles plus tests

- frontend/package.json
- frontend/src/main/components/MenuItemReview/MenuItemReviewForm.js
- frontend/src/stories/components/MenuItemReview/MenuItemReviewForm.stories.js
- frontend/src/tests/components/MenuItemReview/MenuItemReviewForm.test.js
Close #37 
Created form and formTest files for MenuItemReview.
> created form component for MenuItemReview

- frontend/src/main/components/Articles/ArticlesTable.js
- frontend/src/stories/components/Articles/ArticlesTable.stories.js
- frontend/src/tests/components/Articles/ArticlesTable.test.js
Closes #56 
Added the following files: 
- ArticlesTable.js
- ArticlesTable.test.js
- ArticlesTable.stories.js
Link: https://672ac85549183e8fccbb01a1-tvvzucxlis.chromatic.com/?path=/docs/components-articles-articlesform--docs
> added table component for articles plus tests

- frontend/src/fixtures/temp.json
- frontend/src/fixtures/ucsbOrganizationFixtures.js
- frontend/src/index.css
- frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
- frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
- frontend/src/main/utils/UCSBOrganizationUtils.js
- frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
- frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js
- frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
- frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
- frontend/src/tests/utils/UCSBOrganizationUtil.test.js
Closes #20 
https://ucsb-cs156-f24.github.io/team02-f24-05/prs/83/chromatic
> Ishanjain organizations table components and tests

- frontend/src/fixtures/temp.json
- frontend/src/fixtures/ucsbOrganizationFixtures.js
- frontend/src/index.css
- frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js
- frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js
- frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
https://ucsb-cs156-f24.github.io/team02-f24-05/prs/82/chromatic
> organizations form plus tests

- frontend/public/mockServiceWorker.js
- frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemForm.js
- frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.js
- frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js
- frontend/src/stories/components/UCSBDIningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.stories.js
- frontend/src/tests/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.test.js
- frontend/src/tests/utils/UCSBDateUtils.test.js
- frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.js
> Table component for menu items

- frontend/src/main/pages/Articles/ArticlesCreatePage.js
- frontend/src/stories/pages/Articles/ArticlesCreatePage.stories.js
- frontend/src/tests/pages/Articles/ArticlesCreatePage.test.js
Closes #58 
Implemented a create page for articles objects, specifically through the creation of the following files
- ArticlesCreatePage.test.js
- ArticlesCreatePage.js
- ArticlesCreatePage.stories.js
> Articles create page

- frontend/src/App.js
- frontend/src/main/components/Nav/AppNavbar.js
- frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js
- frontend/src/main/pages/MenuItemReview/MenuItemReviewEditPage.js
- frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js
- frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js
- frontend/src/tests/pages/MenuItemReview/MenuItemReviewEditPage.test.js
- frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js
Close #39 
Added MenuItemReview on Nav, App.js.
> added on Nav, App.js

- frontend/src/fixtures/helpRequestFixtures.js
- frontend/src/main/components/HelpRequest/HelpRequestTable.js
- frontend/src/main/utils/HelpRequestUtils.js
- frontend/src/stories/components/HelpRequest/HelpRequestTable.stories.js
- frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
- frontend/src/tests/utils/HelpRequestUtils.test.js
Closes #47 
- Created the table component for HelpRequest along with the associated tests and storybook details
- Passing all tests (coverage and mutation) 100%
https://672ac85549183e8fccbb01a1-lguiymlpot.chromatic.com/
> Created the table component for HelpRequest

- frontend/src/fixtures/helpRequestFixtures.js
- frontend/src/main/components/HelpRequest/HelpRequestTable.js
- frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js
- frontend/src/main/utils/HelpRequestUtils.js
- frontend/src/stories/components/HelpRequest/HelpRequestTable.stories.js
- frontend/src/stories/pages/HelpRequest/HelpRequestIndexPage.stories.js
- frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
- frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js
- frontend/src/tests/utils/HelpRequestUtils.test.js
Closes #50 
- Finished index page for HelpRequest
- Correctly shows all data and allows admin users to create, delete, and edit entries
- Passes all tests 100%
https://672ac85549183e8fccbb01a1-lglsaddrby.chromatic.com/?path=/docs/pages-helprequest-helprequestindexpage--docs
> Edited HelpRequest Index Page

- frontend/src/main/pages/Articles/ArticlesEditPage.js
- frontend/src/stories/pages/Articles/ArticlesEditPage.stories.js
- frontend/src/tests/pages/Articles/ArticlesEditPage.test.js
Closes #60 
Added the edit page for articles + tests and stories. The following files were added to make this change:
- ArticlesEditPage.js
- ArticlesEditPage.test.js
- ArticlesEditPage.stories.js
Link: https://672ac85549183e8fccbb01a1-lhlmfzngfl.chromatic.com/?path=/docs/pages-articles-articleseditpage--docs
> added edit page for articles + tests and stories

- frontend/src/fixtures/temp.json
- frontend/src/index.css
- frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
- frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js
- frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
closes #13 
- UCSBDiningCommonsMenuItemCreatePage.js
- UCSBDiningCommonsMenuItemCreatePage.test.js
- UCSBDiningCommonsMenuItemCreatePage.stories.js
To test this create page, first try inputting any text values to the different boxes and click the create button. If this goes through and you can see your new entry when testing with swagger, that part works. To make sure the invalid formats work, try inputing text that is longer than 50 characters into any of the text boxes, and see if it rejects it.
https://672ac85549183e8fccbb01a1-lhlmfzngfl.chromatic.com/?path=/story/components-ucsbdiningcommonsmenuitems-ucsbdiningcommonsmenuitemform--create
> Create Page for UCSBDiningCommonsMenuItem plus tests and stories

- frontend/public/mockServiceWorker.js
- frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js
- frontend/src/stories/pages/MenuItemReview/MenuItemReviewCreatePage.stories.js
- frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js
Close #40 
editted createPage, createPage.test, createPage.stories files following instructions.
> create page for MenuItemReview plus tests and stories

- frontend/src/fixtures/temp.json
- frontend/src/index.css
- frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.js
- frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
- frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.js
- frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
- frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js
- frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js
- frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.stories.js
- frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js
- frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
- frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemEditPage.test.js
- frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js
- frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.test.js
Closes #15 
Created the following files and used the example code to fill them in:
- UCSBDiningCommonsMenuItemEditPage.js
- UCSBDiningCommonsMenuItemEditPage.test.js
- UCSBDiningCommonsMenuItemEditPage.stories.js
> Edit Page for UCSBDiningCommonsMenuItem plus tests and stories

- frontend/src/fixtures/temp.json
- frontend/src/index.css
- frontend/src/main/components/UCSBDiningCommonsMenuItems/UCSBDiningCommonsMenuItemTable.js
- frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js
- frontend/src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.js
- frontend/src/main/utils/UCSBDiningCommonsMenuItemUtils.js
- frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.stories.js
- frontend/src/stories/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.stories.js
- frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.test.js
- frontend/src/tests/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemIndexPage.test.js
- frontend/src/tests/utils/UCSBDiningCommonsMenuItemUtils.test.js
closes #14 
- UCSBDiningCommonsMenuItemIndexPage.js
- UCSBDiningCommonsMenuItemIndexPage.test.js
- UCSBDiningCommonsMenuItemIndexPage.stories.js
> Index Page for UCSBDiningCommonsMenuItem plus tests and stories

- frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js
- frontend/src/stories/pages/MenuItemReview/MenuItemReviewIndexPage.stories.js
- frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js
Edited indexPage, indexPage.test, indexPage.stories files.
> Index Page for MenuItemReview plus tests and stories

- frontend/src/App.js
- frontend/src/main/components/Nav/AppNavbar.js
- frontend/src/main/pages/RecommendationRequest/RecommendationRequestCreatePage.js
- frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js
- frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js
- frontend/src/tests/pages/RecommendationRequest/RecommendationRequestCreatePage.test.js
- frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js
- frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js
> copy placeholder code

- frontend/src/App.js
- frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js
- frontend/src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js
- frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js
- frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationEditPage.stories.js
- frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js
- frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationEditPage.test.js
- frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
> Edit page for organization plus tests and stories

- frontend/src/fixtures/helpRequestFixtures.js
- frontend/src/main/components/HelpRequest/HelpRequestForm.js
- frontend/src/main/components/HelpRequest/HelpRequestTable.js
- frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js
- frontend/src/stories/pages/HelpRequest/HelpRequestEditPage.stories.js
- frontend/src/tests/components/HelpRequest/HelpRequestForm.test.js
- frontend/src/tests/components/HelpRequest/HelpRequestTable.test.js
- frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js
- frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
Closes #51 
- Added edit page for HelpRequest along with tests and stories
- Made slight modifications to the form component to properly send boolean data to the backend 
- Slightly changed the controller to be able to properly access the solved variable when updating a request
https://672ac85549183e8fccbb01a1-izzkqvdyyh.chromatic.com/?path=/docs/pages-helprequest-helprequesteditpage--docs
> Completed HelpRequest Edit Page

- frontend/src/main/pages/RecommendationRequest/RecommendationRequestEditPage.js
- frontend/src/stories/pages/RecommendationRequest/RecommendationRequestEditPage.stories.js
- frontend/src/tests/pages/RecommendationRequest/RecommendationRequestEditPage.test.js
> recrequest edit page

- frontend/src/main/pages/RecommendationRequest/RecommendationRequestIndexPage.js
- frontend/src/stories/pages/RecommendationRequest/RecommendationRequestIndexPage.stories.js
- frontend/src/tests/pages/RecommendationRequest/RecommendationRequestIndexPage.test.js
Closes #32 
storybook: https://672ac85549183e8fccbb01a1-tkustnetor.chromatic.com/?path=/docs/pages-recommendationrequest-recommendationrequestindexpage--docs
> recrequest index page implemented

- frontend/public/mockServiceWorker.js
- src/test/java/edu/ucsb/cs156/example/integration/HelpRequestIT.java
- All tests pass, testing POST and GET by id
> Added Integration Tests for HelpRequest

- frontend/public/mockServiceWorker.js
- src/test/java/edu/ucsb/cs156/example/web/HelpRequestWebIT.java
- Added end 2 end tests for HelpRequest, checking create, edit and delete for admin users, and that regular users cannot perform those actions
> Added End 2 End tests for HelpRequest

- src/main/resources/db/migration/changes/UCSBOrganization.json
- src/test/java/edu/ucsb/cs156/example/integration/UCSBOrganizationIT.java
> Organizations; Ishan Jain - team03 integration tests

- src/test/java/edu/ucsb/cs156/example/web/UCSBOrganizationWebIT.java
> Organizations: end to end tests

- frontend/public/mockServiceWorker.js
- src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
- src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
- src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
- src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItem.json
- src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java
Backend files for menu item are back
> add backend files again

- src/test/java/edu/ucsb/cs156/example/integration/UCSBDiningCommonsMenuItemIT.java
> integration test for dcmi

- src/test/java/edu/ucsb/cs156/example/web/UCSBDiningCommonsMenuItemWebIT.java
> added e2e test for dcmi

- frontend/src/main/components/Articles/ArticlesForm.js
Added styling to my form to make it more readable.
> Changed Styling

- frontend/public/mockServiceWorker.js
- frontend/src/main/components/MenuItemReview/MenuItemReviewTable.js
- frontend/src/stories/components/MenuItemReview/MenuItemReviewTable.stories.js
- frontend/src/tests/components/MenuItemReview/MenuItemReviewTable.test.js
- src/test/java/edu/ucsb/cs156/example/integration/MenuItemReviewIT.java
- src/test/java/edu/ucsb/cs156/example/web/MenuItemReviewWebIT.java
Added End 2 End tests for menuItemReview.
> menuItemReview end2 end

- frontend/src/main/components/MenuItemReview/MenuItemReviewTable.js
- frontend/src/stories/components/MenuItemReview/MenuItemReviewTable.stories.js
- frontend/src/tests/components/MenuItemReview/MenuItemReviewTable.test.js
- src/test/java/edu/ucsb/cs156/example/integration/MenuItemReviewIT.java
Close #114 
Create Integration test for menuItemReview.
> Integration Test for MenuItemReview

- frontend/src/main/components/Articles/ArticlesForm.js
Added a bit of styling to make the articles table look nicer
> added more styling

- src/test/java/edu/ucsb/cs156/example/web/ArticleWebIT.java
Added files that address the title
> Fixed bugs with end-to-end tests
